# 元数据，请勿修改。
# Default: 0
configVersion = 2

[general]

	# 切换所有模组功能的开关。
	# Default: true
	enabled = true
	# 禁用此项可使模组效果仅限于第一人称视角。
	# Default: true
	enableInThirdPerson = true
	# 由水平转向引起的相机滚动旋转的敏感度。
	# Default: 1.0
	turningRollAccumulation = 0.2
	# 由水平转向引起的相机滚动旋转的最大强度。
	# Default: 1.25
	turningRollIntensity = 0.2
	# 由水平转向引起的相机滚动旋转衰减的平滑度。
	# Default: 1.0
	turningRollSmoothing = 0.8
	# 当玩家闲置足够时间后触发的平滑随机晃动的强度。
	# Default: 0.6
	cameraSwayIntensity = 0.6
	# 当玩家闲置足够时间后触发的平滑随机晃动的频率。
	# Default: 0.16
	cameraSwayFrequency = 0.16
	# 玩家必须闲置多长时间后平滑随机晃动才会开始淡入。
	# Default: 0.15
	cameraSwayFadeInDelay = 0.15
	# 玩家闲置足够时间后，平滑随机晃动完成淡入所需的时间。
	# Default: 5.0
	cameraSwayFadeInLength = 5.0
	# 当玩家在闲置后开始移动时，平滑随机晃动完成淡出所需的时间。
	# Default: 0.75
	cameraSwayFadeOutLength = 0.75
	# 所有屏幕晃动效果的最大强度。
	# Default: 2.5
	screenShakesMaxIntensity = 2.5
	# 屏幕晃动旋转改变方向或振荡的速度。
	# Default: 6.0
	screenShakesMaxFrequency = 6.0
	# 一个 [0..1] 的值，与爆炸引起的屏幕晃动强度相关。
	# Default: 1.0
	explosionTrauma = 1.0
	# 一个 [0..1] 的值，与闪电引发的雷声引起的屏幕晃动强度相关。
	# Default: 0.05
	thunderTrauma = 0.05
	# 一个 [0..1] 的值，与任何摆动玩家手臂的动作引起的屏幕晃动强度相关。最好保持非常低的值。
	# Default: 0.03
	handSwingTrauma = 0.03

[walking]

	# 由平移（侧向水平移动）引起的相机滚动旋转的强度。
	# Default: 10.0
	strafingRollFactor = 0.2
	# 由前后移动引起的相机俯仰旋转的强度。
	# Default: 7.0
	forwardVelocityPitchFactor = 0.2
	# 由垂直移动引起的相机俯仰旋转的强度。
	# Default: 2.5
	verticalVelocityPitchFactor = 0.2
	# 由水平移动引起的相机俯仰和滚动旋转的平滑度。
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 0.16
	# 由垂直移动引起的相机俯仰旋转的平滑度。
	# Default: 1.0
	verticalVelocitySmoothingFactor = 0.16

[swimming]

	# 由平移（侧向水平移动）引起的相机滚动旋转的强度。
	# Default: -30.0
	strafingRollFactor = -1.0
	# 由前后移动引起的相机俯仰旋转的强度。
	# Default: 21.0
	forwardVelocityPitchFactor = 0.2
	# 由垂直移动引起的相机俯仰旋转的强度。
	# Default: 7.5
	verticalVelocityPitchFactor = 0.2
	# 由水平移动引起的相机俯仰和滚动旋转的平滑度。
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 0.16
	# 由垂直移动引起的相机俯仰旋转的平滑度。
	# Default: 1.0
	verticalVelocitySmoothingFactor = 0.16

[flying]

	# 由平移（侧向水平移动）引起的相机滚动旋转的强度。
	# Default: -10.0
	strafingRollFactor = -1.0
	# 由前后移动引起的相机俯仰旋转的强度。
	# Default: 7.0
	forwardVelocityPitchFactor = 0.2
	# 由垂直移动引起的相机俯仰旋转的强度。
	# Default: 2.5
	verticalVelocityPitchFactor = 0.2
	# 由水平移动引起的相机俯仰和滚动旋转的平滑度。
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 0.16
	# 由垂直移动引起的相机俯仰旋转的平滑度。
	# Default: 1.0
	verticalVelocitySmoothingFactor = 0.16

[mounts]

	# 由平移（侧向水平移动）引起的相机滚动旋转的强度。
	# Default: 20.0
	strafingRollFactor = 0.2
	# 由前后移动引起的相机俯仰旋转的强度。
	# Default: 7.0
	forwardVelocityPitchFactor = 0.2
	# 由垂直移动引起的相机俯仰旋转的强度。
	# Default: 2.5
	verticalVelocityPitchFactor = 0.2
	# 由水平移动引起的相机俯仰和滚动旋转的平滑度。
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 0.16
	# 由垂直移动引起的相机俯仰旋转的平滑度。
	# Default: 1.0
	verticalVelocitySmoothingFactor = 0.16

[vehicles]

	# 由平移（侧向水平移动）引起的相机滚动旋转的强度。
	# Default: 5.0
	strafingRollFactor = 0.2
	# 由前后移动引起的相机俯仰旋转的强度。
	# Default: 1.75
	forwardVelocityPitchFactor = 0.2
	# 由垂直移动引起的相机俯仰旋转的强度。
	# Default: 5.0
	verticalVelocityPitchFactor = 0.2
	# 由水平移动引起的相机俯仰和滚动旋转的平滑度。
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 0.16
	# 由垂直移动引起的相机俯仰旋转的平滑度。
	# Default: 1.0
	verticalVelocitySmoothingFactor = 0.16
